version: '3.8'

services:
  nextjs-app:
    container_name: nextjs-app
    build:
      context: ${APP_ROOT}
      dockerfile: infra/docker/Dockerfile
      args:
        APP_ENV: "dev"
    environment:
      - NODE_ENV=development
    env_file:
      - ${APP_ROOT}/infra/config/.env
    networks:
      - app-network
    ports:
      - 3000:3000
    volumes:
      - ${APP_ROOT}:/app
      - /app/node_modules
      - /app/.next
    entrypoint: /bin/sh -c "npm install && npm run dev"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=paynah
    networks:
      - app-network
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
